# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import coffee_cup_pb2 as coffee__cup__pb2


class CoffeeCupConsumersStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ListConsumers = channel.unary_stream(
        '/coffeecup.CoffeeCupConsumers/ListConsumers',
        request_serializer=coffee__cup__pb2.Empty.SerializeToString,
        response_deserializer=coffee__cup__pb2.Consumer.FromString,
        )


class CoffeeCupConsumersServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ListConsumers(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CoffeeCupConsumersServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ListConsumers': grpc.unary_stream_rpc_method_handler(
          servicer.ListConsumers,
          request_deserializer=coffee__cup__pb2.Empty.FromString,
          response_serializer=coffee__cup__pb2.Consumer.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'coffeecup.CoffeeCupConsumers', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
