# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: coffee-cup.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='coffee-cup.proto',
  package='coffeecup',
  syntax='proto3',
  serialized_pb=_b('\n\x10\x63offee-cup.proto\x12\tcoffeecup\"\x07\n\x05\x45mpty\"2\n\x08\x43onsumer\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x65\x62t\x18\x03 \x01(\x02\x32P\n\x12\x43offeeCupConsumers\x12:\n\rListConsumers\x12\x10.coffeecup.Empty\x1a\x13.coffeecup.Consumer\"\x00\x30\x01\x42-\n\x12ru.sppps.coffeecupB\x0fRouteGuideProtoP\x01\xa2\x02\x03RTGb\x06proto3')
)




_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='coffeecup.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=38,
)


_CONSUMER = _descriptor.Descriptor(
  name='Consumer',
  full_name='coffeecup.Consumer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='coffeecup.Consumer.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='coffeecup.Consumer.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='debt', full_name='coffeecup.Consumer.debt', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=90,
)

DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['Consumer'] = _CONSUMER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), dict(
  DESCRIPTOR = _EMPTY,
  __module__ = 'coffee_cup_pb2'
  # @@protoc_insertion_point(class_scope:coffeecup.Empty)
  ))
_sym_db.RegisterMessage(Empty)

Consumer = _reflection.GeneratedProtocolMessageType('Consumer', (_message.Message,), dict(
  DESCRIPTOR = _CONSUMER,
  __module__ = 'coffee_cup_pb2'
  # @@protoc_insertion_point(class_scope:coffeecup.Consumer)
  ))
_sym_db.RegisterMessage(Consumer)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\022ru.sppps.coffeecupB\017RouteGuideProtoP\001\242\002\003RTG'))

_COFFEECUPCONSUMERS = _descriptor.ServiceDescriptor(
  name='CoffeeCupConsumers',
  full_name='coffeecup.CoffeeCupConsumers',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=92,
  serialized_end=172,
  methods=[
  _descriptor.MethodDescriptor(
    name='ListConsumers',
    full_name='coffeecup.CoffeeCupConsumers.ListConsumers',
    index=0,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_CONSUMER,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_COFFEECUPCONSUMERS)

DESCRIPTOR.services_by_name['CoffeeCupConsumers'] = _COFFEECUPCONSUMERS

try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities


  class CoffeeCupConsumersStub(object):
    # missing associated documentation comment in .proto file
    pass

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.ListConsumers = channel.unary_stream(
          '/coffeecup.CoffeeCupConsumers/ListConsumers',
          request_serializer=Empty.SerializeToString,
          response_deserializer=Consumer.FromString,
          )


  class CoffeeCupConsumersServicer(object):
    # missing associated documentation comment in .proto file
    pass

    def ListConsumers(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_CoffeeCupConsumersServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'ListConsumers': grpc.unary_stream_rpc_method_handler(
            servicer.ListConsumers,
            request_deserializer=Empty.FromString,
            response_serializer=Consumer.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'coffeecup.CoffeeCupConsumers', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaCoffeeCupConsumersServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    # missing associated documentation comment in .proto file
    pass
    def ListConsumers(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaCoffeeCupConsumersStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    # missing associated documentation comment in .proto file
    pass
    def ListConsumers(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      # missing associated documentation comment in .proto file
      pass
      raise NotImplementedError()


  def beta_create_CoffeeCupConsumers_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('coffeecup.CoffeeCupConsumers', 'ListConsumers'): Empty.FromString,
    }
    response_serializers = {
      ('coffeecup.CoffeeCupConsumers', 'ListConsumers'): Consumer.SerializeToString,
    }
    method_implementations = {
      ('coffeecup.CoffeeCupConsumers', 'ListConsumers'): face_utilities.unary_stream_inline(servicer.ListConsumers),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_CoffeeCupConsumers_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('coffeecup.CoffeeCupConsumers', 'ListConsumers'): Empty.SerializeToString,
    }
    response_deserializers = {
      ('coffeecup.CoffeeCupConsumers', 'ListConsumers'): Consumer.FromString,
    }
    cardinalities = {
      'ListConsumers': cardinality.Cardinality.UNARY_STREAM,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'coffeecup.CoffeeCupConsumers', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
