"""User model added

Revision ID: 2df8e41a90f6
Revises: 
Create Date: 2017-09-14 13:11:45.141695

"""
from alembic import op
import sqlalchemy as sa
from passlib.context import CryptContext

# revision identifiers, used by Alembic.
revision = '2df8e41a90f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    users_table = op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.Column('pwdhash', sa.String(length=128), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    pwd_context = CryptContext(schemes=["pbkdf2_sha256"])
    op.bulk_insert(users_table, [
        {'username': 'admin', 'pwdhash': pwd_context.hash('admin:12345'), 'is_admin': True}
        ])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
